version: "2"

services:

  purchaseapi:
    image: cfndiaye/purchase-api-stage:latest
    ports:
       - 8080:80
       - 11443:443
    environment:
       - ASPNETCORE_ENVIRONMENT=Production
       - ASPNETCORE_URLS=https://+;http://+
       - ASPNETCORE_Kestrel__Certificates__Default__Password=58781681
       - ASPNETCORE_Kestrel__Certificates__Default__Path=/Logs/cert.pfx
    volumes:
       - type: bind
         source: /home/dakar-hightech/homes/PurchaseManagerStage/Prod-api
         target: /Logs
  purchaseblazor: 
    image: cfndiaye/purchase-blazor-stage:latest
    ports:
       - 8081:80
       - 12443:443
    volumes:
       - type: bind
         source: /home/dakar-hightech/homes/PurchaseManagerStage/Prod-blazor
         target: /Logs
    