# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  docker: circleci/docker@1.7.0

workflows:
    deploy-api-workflow:
      jobs:
        - docker/publish:
            dockerfile: Dockerfile 
            tag: latest
            image: cfndiaye/purchase-api-stage
            docker-password: DOCKER_PASSWORD 
            docker-username: DOCKER_LOGIN 
            docker-context: . 
        - docker/publish:
            dockerfile: PurchaseBlazor/Dockerfile 
            docker-context: . 
            tag: latest
            image: cfndiaye/purchase-blazor-stage 



